### ISSUE TITLE
Laser DOS v1.1

### ISSUE THREAD

**Issue by bushy555** [yuanb/dd20emu#39]
Hi Yuan,
Just reading through your very interesting project.
I noticed that you have BASIC ROM version 1.1
This is the only ROM version that we do not have in the entire VZ/Laser software collection.
Is there any chance of downloading this into a binary format and sharing ?

A few of us enthusiasts on the VZ/Laser facebook page would love to have this BASIC ROM version added to our collection.
Thanks
-dave.

**Comment by yuanb** [comment]
Hi Dave,
Certainly, I can help to dump it. I will have a look as soon I have a chance

**Comment by bushy555** [comment]
Thankyou - that would be wonderful.! If I can help you in anyway, please sing out.

I was the *stupid* person whom hand-typed out v1.2 rom way back in late '98 for the first emulator 'vzem' written by Guy Thomason. Took me six weeks with good old Windows DEBUG and tens & tens of VZ printouts of the ROM in hex.
Cheers

**Comment by yuanb** [comment]
> Thankyou - that would be wonderful.! If I can help you in anyway, please sing out.
> 
> I was the _stupid_ person whom hand-typed out v1.2 rom way back in late '98 for the first emulator 'vzem' written by Guy Thomason. Took me six weeks with good old Windows DEBUG and tens & tens of VZ printouts of the ROM in hex. Cheers

The ROM chips are a pair of Mitsubishi M5L2764K. Last time I tried （in 2019), I couldn't get stable reading from my programmer. I will try again. They are fine on VZ200 machine though.

**Comment by yuanb** [comment]
@bushy555 Done Check FB posts
